### ISSUE TITLE
feature: To extract Audio from PPT files and merge them under a single .wav file

### ISSUE THREAD

**Issue by artemis-i-guess** [metafy-social/python-scripts#147]
### Is your feature request related to a problem? Please describe
Extracting audio from PPT files , which we may use other software to do so, can be done simply by running a simple .py script

### Describe the solution you'd like
using pydub library we cover the audio part, with zipfile and shutil modules we solve the opening,copying,saving etc part.

**Comment by bartick** [comment]
Didn't quite get your point in it. Not sure why someone will store a audio in ppt files. 

@advaita-saha @kriptonian1 please look into this one

**Comment by advaita-saha** [comment]
@artemis-i-guess go ahead
