### ISSUE TITLE
NumberToWord

### ISSUE THREAD

**Issue by theadeyemiolayinka** [metafy-social/python-scripts#455]
### Is your feature request related to a problem? Please describe
Number to word converter in python

### Describe the solution you'd like
A python script to convert numbers to word format.

**Comment by Ramakm** [comment]
Please assign me this issue under Hacktoberfest2022.

**Comment by theadeyemiolayinka** [comment]
@Ramakm If you want to solve a similar problem, the Contributing guide suggests you create an issue.

**Comment by Ramakm** [comment]
@theadeyemiolayinka okay.
