### ISSUE TITLE
Find the location of an IP address.

### ISSUE THREAD

**Issue by money8203** [metafy-social/python-scripts#54]
Sometimes you'll need to know the location of an IP address, whether it's your own or that of a site you're using.

One use-case for this is when you want to send login information to users for your website.

IHere we're going to see how you can find the location of an IP address using Python.

**Comment by advaita-saha** [comment]
@money8203 assigned to you

**Comment by money8203** [comment]
@advaita-saha  done can check now !!    #62

**Comment by money8203** [comment]
I have deleted the old file and created a new one and new pull request also.

**Comment by atharva360** [comment]
can you assign me this task please..

**Comment by muratonuryildirim** [comment]
I would like to create a PR to that issue.

**Comment by advaita-saha** [comment]
Sorry @atharva360 @muratonuryildirim 
According to our policy the assignee is given 3weeks to create a PR and merge it

**Comment by muratonuryildirim** [comment]
Okay, good to know :)
